version: '2'

services:
  web:
    image: ebuzaneli/xampp_mysql_php5
    
    hostname: xampp-buzza
    container_name: xampp-buzza
    
    ports:
      - 8080:80
      - 33306:3306
      - 443:443
      - 2222:22
      
    volumes:
      - /Users/eniomarcelobuzaneli/Documents/Docker/xamppphp5/www:/opt/lampp/htdocs
      - /Users/eniomarcelobuzaneli/Documents/Docker/xamppphp5/php/php.ini:/opt/lampp/etc/php.ini
      - /Users/eniomarcelobuzaneli/Documents/Docker/xamppphp5/phpmyadmin/config.inc.php:/opt/lampp/phpmyadmin/config.inc.php
      - /Users/eniomarcelobuzaneli/Documents/Docker/xamppphp5/mysql:/opt/lampp/var/mysql
      
    environment:
      - TZ=America/Campo_Grande
    #links:
    #  - db
    #depends_on:
    #  - db
    restart: always
    networks:
      - buzza-xampp-network
      
      
networks:
  buzza-xampp-network:
    driver: bridge
